Repository Empty2k12/influxdb-rust, pull requests merged in 2019-10, with the labels that each got.

#15 Removed usage of `itertools`
  Cargo.lock
  Cargo.toml
  src/query/write_query.rs
Labels: Type of Change: Minor, Type: Enhancement

#18 Contributing Guidelines, Code of Conduct and Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: Type of Change: Medium, Type: Governance

#22 Don't commit Cargo.lock
  .gitignore
  Cargo.lock
Labels: Type of Change: Minor, Type: Best Practice

#21 Replace use of `Any` by an enum
  src/client/mod.rs
  src/query/mod.rs
Labels: Hacktoberfest, Status: Merge when CI passes, Type of Change: Medium, Type: Enhancement

#26 Fix and Enforce Clippy Lints
  .travis.yml
  src/client/mod.rs
  src/integrations/serde_integration.rs
  src/query/mod.rs
  src/query/read_query.rs
  tests/integration_tests.rs
Labels: Status: Merge when CI passes, Type of Change: Minor, Type: Best Practice

#27 Prefix `InfluxDb` of type names are redundant
  README.md
  src/client/mod.rs
  src/error.rs
  src/integrations/serde_integration.rs
  src/lib.rs
  src/query/mod.rs
  src/query/read_query.rs
  src/query/write_query.rs
  tests/integration_tests.rs
Labels: Type of Change: Medium, Type: Enhancement

#30 Replace ToString with Into<String>
  src/client/mod.rs
  src/query/mod.rs
  src/query/read_query.rs
  src/query/write_query.rs
  tests/integration_tests.rs
Labels: Status: Merge when CI passes, Type of Change: Minor, Type: Enhancement

#29 Switch to `cargo-readme` for README generation
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CONTRIBUTING.md
  README.md
  README.tpl
  auxiliary/check_readme_consistency.sh
  auxiliary/update_cargo-readme.sh
  src/lib.rs
Labels: Hacktoberfest, Status: Merge when CI passes, Type of Change: Medium, Type: Chore

#32 Add `+ Send` to futures
  src/client/mod.rs
  src/integrations/serde_integration.rs
Labels: Hacktoberfest, Status: Pending Updates, Type of Change: Minor, Type: Enhancement

#37 Allow writing Option<T>
  src/query/write_query.rs
  tests/integration_tests.rs
Labels: Status: Merge when CI passes, Type of Change: Minor, Type: Enhancement

#40 Lowercase Timestamps variants
  README.md
  src/client/mod.rs
  src/lib.rs
  src/query/mod.rs
  src/query/write_query.rs
  tests/integration_tests.rs
Labels: Hacktoberfest, Status: Merge when CI passes, Type of Change: Minor, Type: Enhancement

#44 Remove Code Coverage
  .travis.yml
  Cargo.toml
  README.md
  README.tpl
Labels: Status: Review in Progress, Type of Change: Minor, Type: Chore

#41 Chrono types for Timestamp
  .travis.yml
  Cargo.toml
  README.md
  src/lib.rs
  src/query/consts.rs
  src/query/mod.rs
Labels: Status: Review in Progress, Type of Change: Medium, Type: Enhancement
