Repository Empty2k12/influxdb-rust, pull requests merged in 2020-10, with the labels that each got.

#70 Replace failure with thiserror
  influxdb/Cargo.toml
  influxdb/src/client/mod.rs
  influxdb/src/error.rs
  influxdb/src/integrations/serde_integration/mod.rs
  influxdb/src/lib.rs
Labels: Type of Change: Minor, Type: Chore

#69 Allow `GROUP BY` queries by providing `deserialize_next_tagged` to deserialize the group fields
  influxdb/src/integrations/serde_integration/de.rs
  influxdb/src/integrations/serde_integration/mod.rs
  influxdb/tests/integration_tests.rs
Labels: Type of Change: Medium, Type: Enhancement

#71 Document releasing process
  RELEASING.md
Labels: Type: Governance
