Repository Empty2k12/influxdb-rust, pull requests merged in 2020-11, with the labels that each got.

#73 Refactor client
  Cargo.toml
  benches/Cargo.toml
  benches/client.rs
  influxdb/Cargo.toml
  influxdb/src/client/mod.rs
  influxdb/src/integrations/serde_integration/mod.rs
Labels: Status: Awaiting Response, Type: Best Practice

#72 Add async-std support and replaced reqwest with surf (#58)
  README.md
  benches/client.rs
  influxdb/Cargo.toml
  influxdb/src/client/mod.rs
  influxdb/src/error.rs
  influxdb/src/integrations/serde_integration/mod.rs
  influxdb/src/lib.rs
  influxdb/src/query/write_query.rs
  influxdb/tests/derive_integration_tests.rs
  influxdb/tests/integration_tests.rs
Labels: Status: Review in Progress, Type: Enhancement

#75 Fix deserialization of Series in case of no values.
  influxdb/src/integrations/serde_integration/de.rs
Labels: Type of Change: Minor, Type: Bug
